### ISSUE TITLE
Display current status and progress

### ISSUE THREAD

**Issue by glarrain** [IlianIliev/Simple-Site-Checker#2]
It would be great to know how is the program doing while executing. For example, if there are too many links, the user can't know if the tool is doing good, is stuck, is close to finish, etc. I think a simple an clean way to report is the way unittest reports the execution: for eah test, a dot is sucess, F is fail, E is error. Then at the end displays an execution summary.

**Comment by IlianIliev** [comment]
Thanks for the idea. I'll try to make this as soon as possible. Meanwhile have you checked the -v option?

**Comment by glarrain** [comment]
Ups, I had not. Well, that does help to check progress, although my proposal still stands, because between -v 1 and -v2 there's quite a difference in output (well, that happens when log level is changed).

Thanks. Let me know if you need help with anything!

**Comment by IlianIliev** [comment]
I found a simple way to do this using sys.stdout.write() but I am still a bit hesitant about the mix of logging and stdout. Any idea how can I use the logging module without printing to a new line every time?

**Comment by glarrain** [comment]
Well, I think logging should be left out as it is right now, and set up link checking functionality as it were doing assertions in test cases. Checking `unittest.case.TestCase.run`, I can see several functions from `unittest.runner.TextTestResult` are called: `addSuccess`, `addError`, `addFailure`, `printErrors`, `printErrorList`.

What do you think?

**Comment by IlianIliev** [comment]
After a deep thought I decided that the dot/F/E output will be inconsistent with the other logging. At the same time I wanted to keep no output if there is no error on verbose 0 because the script is meant to be run with cron. So I just added an info message for each tested URL.
