### ISSUE TITLE
Publish as module to PYPI

### ISSUE THREAD

**Issue by summerisgone** [IlianIliev/Simple-Site-Checker#3]
I'm very much like your script. I'd like also to include it into my monitoring system. Сould you please publish your project at python package index?

**Comment by IlianIliev** [comment]
I am glad you like it.
The package is ready and available at https://pypi.python.org/pypi/SimpleSiteChecker/0.1.0

**Comment by summerisgone** [comment]
Thank you for you attention!

2013/9/23 eng. Ilian Iliev notifications@github.com

> I am glad you like it.
> The package is ready and available at
> https://pypi.python.org/pypi/SimpleSiteChecker/0.1.0
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IlianIliev/Simple-Site-Checker/issues/3#issuecomment-24887288
> .

## 

Иван Громов
